### ISSUE TITLE
WASM to X86 Backend

### ISSUE THREAD

**Issue by Shaikh-Ubaid** [lcompilers/lpython#1222]
There is an idea to implement a `wasm` to `x86` backend. We have to benchmark `ASR->x86` and `ASR->WASM->x86`. If the performance difference is not much, then the big advantage of `WASM->x86` would (hopefully) be that it would be a easier and quicker for us to deliver a working backend.

- We can start with 32bit, since it is already figured out, unless it is more complicated,then we can just do 64 bit.

***Notes:**
- This was first discussed at https://github.com/certik/test_wasm/pull/4#issuecomment-1135992438 (last line) and https://github.com/certik/test_wasm/pull/4#issuecomment-1136375282 (last paragraph).

**Comment by Shaikh-Ubaid** [comment]
For `x86` do we need the binary format or text based format or both?

**Comment by certik** [comment]
I think you can use the X86 assembler, which just generates a binary, but in Debug mode it can also do a text format.

Alternatively, we just do a binary, and then do x86 -> text assembly.

**Comment by Shaikh-Ubaid** [comment]
https://github.com/lcompilers/lpython/blob/fc08c06fbcbc60d1000b7da0f2da4f8a72f3c622/src/libasr/codegen/asr_to_wasm.cpp#L1935-L1949

In `wasm`, when printing strings, we have the length of the string and its location in memory onto the stack. In `x86` as well, when there is a call to print string, we would be having the length of the string and its memory location onto the `x86` stack. The concern here is that the memory location of the string is not available with the `wasm->x86` backend (during compile-time), but instead is available with `x86` (during runtime, since the location is already onto the stack). Thus, if we (somehow) create a label for each string, we are unable to reference the label for a particular string (the label and the string's memory might not be same or we might not be able to create a relation between them). It seems we might need to dynamically allocate strings in `x86`.

**Comment by Shaikh-Ubaid** [comment]
>In wasm, when printing strings, we have the length of the string and its location in memory onto the stack.

This idea of printing strings using its length and memory location is more of our own concept/choice. It is possible that `WASI` might have different mechanism of printing string. At the moment, we do not have support for `WASI`.

**Comment by Shaikh-Ubaid** [comment]
Prospective Roadmap:
- [ ] support printing `strings`
- [ ] support `if else` (thus support `assert`)
- [ ] support `stop` and `error stop` (we need `error stop` for `CI` tests)
- [ ] support `wasm_x86` at the `CI`
- [ ] support printing negative integers
- [ ] support `loops` (hopefully including `continue` and `break`)
- [ ] support `floating point` numbers (and operations on them)

**Comment by Thirumalai-Shaktivel** [comment]
@Shaikh-Ubaid sorry, I was a little busy with this PR: https://github.com/lcompilers/lpython/pull/1256.
So, were you able to figure out a way for the [comment](https://github.com/lcompilers/lpython/issues/1222#issuecomment-1296286509)?
I'm interested in working on this issue alongside with you! What are you working now?

**Comment by certik** [comment]
Here is how to benchmark:
```python
N = 10000

A_functions = ""
calls = ""
for i in range(N):
    func_A = f"""
def A{i}(x: i32) -> i32:
    y: i32
    z: i32
    y = {i}
    z = 5
    x = x + y * z
    return x
"""
    A_functions += func_A
    calls += f"    y = A{i}(y)\n"

source = f"""\
from ltypes import i32

{A_functions}

def Driver(radius: i32) -> i32:
    y: i32
    y = radius
{calls}
    return y

def Main0():
    print(Driver(5))

Main0()
"""

print(source)
```

**Comment by Shaikh-Ubaid** [comment]
>So, were you able to figure out a way for the https://github.com/lcompilers/lpython/issues/1222#issuecomment-1296286509?

There is a hackish idea to support printing strings in the `wasm_x86` backend. I am not sure if it would work but I am positive.

>I'm interested in working on this issue alongside with you! What are you working now?

Sure, we can work together. I am hoping to follow the roadmap shared here https://github.com/lcompilers/lpython/issues/1222#issuecomment-1299557743. You can proceed with supporting `if else` in the `wasm_x86`. Please feel free to get in touch for any clarification/query related to `wasm` or `wasm_x86` backends.

**Comment by certik** [comment]
Here are the timing results. With `N = 10000`, the above script produces a file with 90,015 lines. Here are the results (best timing each):
```console
$ time lpython --backend=llvm a.py -o a_llvm.x
lpython --backend=llvm a.py -o a_llvm.x  2.94s user 0.10s system 99% cpu 3.034 total
$ time lpython --backend=x86 a.py -o a_x86.x
lpython --backend=x86 a.py -o a_x86.x  0.09s user 0.01s system 93% cpu 0.104 total
$ time lpython --backend=wasm_x86 a.py -o a_wasm_x86.x
lpython --backend=wasm_x86 a.py -o a_wasm_x86.x  0.11s user 0.01s system 95% cpu 0.129 total
```
The programs runs on x86 Linux:
```
$ ./a_wasm_x86.x 
249975005$ ./a_x86.x 
249975005
$ 
```
Summary for this particular example:

| Backend | Time | Speedup over LLVM |
| --- | --- | --- |
| LLVM | 3.034 | 1x |
| WASM x86 | 0.129 | 23.5x |
| x86 | 0.104 | 29.2x |

**Comment by certik** [comment]
@Shaikh-Ubaid can you please submit a PR with the script in https://github.com/lcompilers/lpython/issues/1222#issuecomment-1301031741 and put it into `src/bin`? That way we can use it for benchmarking.

**Comment by Shaikh-Ubaid** [comment]
>@Shaikh-Ubaid can you please submit a PR with the script in https://github.com/lcompilers/lpython/issues/1222#issuecomment-1301031741 and put it into src/bin? That way we can use it for benchmarking.

Submitted here https://github.com/lcompilers/lpython/pull/1260

**Comment by Shaikh-Ubaid** [comment]
**Debug Mode** Benchmark results for `N = 10000` on AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx @1.6GHz
```bash
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time python bench.py 
249975005

real    0m0.461s
user    0m0.396s
sys     0m0.064s
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time lpython bench.py --backend llvm
249975005

real    1m55.329s
user    1m55.093s
sys     0m0.154s
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time lpython bench.py --backend x86

real    0m24.622s
user    0m24.588s
sys     0m0.028s
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time lpython bench.py --backend wasm_x86

real    0m48.122s
user    0m47.993s
sys     0m0.081s
```
---

**Release Mode** Benchmark results for `N = 10000` on AMD Ryzen 5 2500U with Radeon Vega Mobile Gfx @1.6GHz
```bash
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time python bench.py 
249975005

real    0m0.511s
user    0m0.412s
sys     0m0.095s
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time lpython bench.py --backend llvm
249975005

real    0m6.126s
user    0m6.021s
sys     0m0.084s
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time lpython bench.py --backend x86

real    0m0.282s
user    0m0.241s
sys     0m0.040s
(lp) ubaid@ubaid-Lenovo-ideapad-330-15ARR:~/OpenSource/lpython$ time lpython bench.py --backend wasm_x86

real    0m0.369s
user    0m0.308s
sys     0m0.061s
```

---

**Note**: The above results (of both **Debug** mode and **Release** mode) are for single time execution.

**Comment by Thirumalai-Shaktivel** [comment]
[This](https://stackoverflow.com/questions/19886399/assembly-masm-dealing-with-negative-integers)  might help with printing negative numbers, I looking for some other resources.

**Comment by Thirumalai-Shaktivel** [comment]
How do I implement `asm_shr_r32_mm8`?
Just like:
https://github.com/lcompilers/lpython/blob/50848976e8d32dd1f0ebdad3c15554aba2521fe9/src/libasr/codegen/x86_assembler.h#L692-L701
Where to look for `hex value` for `shr`?
@certik @Shaikh-Ubaid

**Comment by Thirumalai-Shaktivel** [comment]
@Shaikh-Ubaid, I have a doubt?https://github.com/lcompilers/lpython/blob/d4a6d5360ca520d9a25d658e6660cb39a2eda4e2/src/libasr/codegen/wasm_to_x86.cpp#L101-L102
Here`ConstI32` value is pushed into the stack, right? Does this mean it will be stored in the `eax`?
Instead why not we `mov value to eax` and `pop the eax` in the ConstI32 visitor?

**Comment by Shaikh-Ubaid** [comment]
>HereConstI32 value is pushed into the stack, right? Does this mean it will be stored in the eax?

It will be stored in the stack. It will not be stored in `eax`, I think.

>Instead why not we mov value to eax and pop the eax in the ConstI32 visitor?

We need the value to be on top of stack. Do you mean to first store the value in `eax` and then push the `eax` value onto stack? It would be a two step process and hence not be efficient, since we can achieve the same by directly pushing onto stack.

**Comment by Thirumalai-Shaktivel** [comment]
Okay, After pushing the value into stack. Do you use that value, later in the process?

**Comment by Thirumalai-Shaktivel** [comment]
I'm a little confused here, Can you share some useful resource to better understand the working of `eax`, `ebx`, `stack` ...?

**Comment by Shaikh-Ubaid** [comment]
>Do we use that value, later in the process? Or How do we use that?

Yes, the other instructions that follow use it. For example, After the `I32Const`, there could be an instruction `I32Neg` (hypothetical example) which would use the value on top of stack (it pops it to use it), negate it and then push back onto stack.

**Comment by Thirumalai-Shaktivel** [comment]
Cool, got it. Thanks

**Comment by Shaikh-Ubaid** [comment]
>I'm a little confused here, Can you share some useful resources to better understand the workings of eax, ebx, stack ...?

I mostly used a combination of https://www.intel.com/content/dam/www/public/us/en/documents/manuals/64-ia-32-architectures-software-developer-instruction-set-reference-manual-325383.pdf (also shared on Zulip, it seems slightly big), Google Search and (some) Youtube.

I did not find any specific (great) resource for `x86` yet. If you find something, please let me know.

**Comment by Shaikh-Ubaid** [comment]
> support floating point numbers (and operations on them)

@certik do we need support for floating point numbers in the `x86` and `wasm_x86` backends? It seems for floating point numbers, we would need to extend `x86_assembler.cpp`.

**Comment by certik** [comment]
Yes, we should do floating point numbers.

**Comment by certik** [comment]
We now have WASM->x86 backends (both 32 and 64 bit), so I am closing this issue. We can open specific issues for missing features.
