### ISSUE TITLE
Roadmap

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#155]
Here is a roadmap that we can follow:

* [x] Finish runtime library like `comptime_eval.h` in LFortran
* [x] Be able to call a function like `lpython_str_format` that is our own LPython implementation of the `%` formatting operator, this function will be inserted by the frontend (tested by #256, which calls `_lpython_imag`)
* [x] Implement the rest of `str` functionality (mostly in the LLVM backend) and fix all bugs related to strings (the remaining bug seems to be #273)
* [x] C interop (#3)
* [x] Generic functions (#141)
* [ ] NumPy support (#5)

This should allow us to implement large parts of the runtime library, and get LPython off the ground. After the above works, the other missing features that we need to implement are:

* [ ] Generics (#154)
* [ ] Interactivity (#329)

Other (lower priority):

* [ ] Improvements to C interop: #545

**Comment by Shaikh-Ubaid** [comment]
Sorry, the unpinning happened by mistake. For a moment I thought that it was a popup/notification, but later realized that it was a pinned issue.

I will take care next time.

**Comment by certik** [comment]
I'll use this issue to link to issues of high priority:

* #992
* #996

We'll figure out a detailed roadmap. Until then, feel free to work towards any of the issues here.

**Comment by certik** [comment]
The highest priority issues I think right now are:

* https://github.com/lcompilers/lpython/issues/1305
* https://github.com/lcompilers/lpython/pull/1297

**Comment by certik** [comment]
* https://github.com/lcompilers/lpython/issues/1575

**Comment by certik** [comment]
Closing in favor of #1600.
