### ISSUE TITLE
Initial TODO for LPython

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#16]
* [ ] Rename the `lfortran` binary to `lpython`
* [ ] Make `--show-python-ast` just `--show-ast`, the same with `--show-asr`, `--show-cpp`
* [ ] Get `--show-llvm` working
* [ ] Get compiling to binaries working
* [ ] Merge `a.py` with `lpython`, probably using Cython

**Comment by Thirumalai-Shaktivel** [comment]
Hi @certik, Currently I'm figuring out a way to merge `a.py` with lpython, so there will be no need to run `python a.py` every time. 
How to do it?? Can you please brief out the implementation so that I can look around...

**Comment by Smit-create** [comment]
> * Add tests (run_tests.py for ASR mainly, and then integration_tests, we can simply call lpython on the main file and then run it, probably adapting cmake, so that we can use ctest to execute)

Should I work on this?

**Comment by Thirumalai-Shaktivel** [comment]
Yes, Of course. Add all the test files into the `tests` folder for now.
Regarding the extension, keep it `*.py` for now. Later, we can change as per our needs.
Also, Can you please add all the tests which you mentioned in the GitLab MR(lfortran: py branch)? [Like break, AugAssign, etc...]
