### ISSUE TITLE
LPython Roadmap

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1600]
* [ ] https://github.com/lcompilers/lpython/issues/1575
* [ ] https://github.com/lcompilers/lpython/issues/154
* [ ] https://github.com/lcompilers/lpython/issues/329
* [ ] https://github.com/lcompilers/lpython/issues/545
* [ ] https://github.com/lcompilers/lpython/issues/305
* [ ] https://github.com/lcompilers/lpython/issues/1599
* [ ] https://github.com/lcompilers/lpython/issues/992
* [ ] https://github.com/lcompilers/lpython/issues/996
* [ ] https://github.com/lcompilers/lpython/issues/703

Old issue was https://github.com/lcompilers/lpython/issues/155.
