### ISSUE TITLE
Symbolic TODO

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#1987]
* [x] Initial implementation: https://github.com/lcompilers/lpython/pull/1846
* [x] Finish the PR: https://github.com/lcompilers/lpython/pull/1964
* [x] Implement stack for expression evaluation: https://github.com/lcompilers/lpython/pull/2051
* [x] Implement `assert x == S(0)`: https://github.com/lcompilers/lpython/pull/2057
* [x] Free variables properly (via the stack): https://github.com/lcompilers/lpython/pull/2064
* [x] Add more elementary functions (sin, cos, etc.) https://github.com/lcompilers/lpython/pull/2094
* [x] Implement some operations like diff: https://github.com/lcompilers/lpython/pull/2077

...

* [x] We can see how to do the above in the LLVM backend
    * [x] See https://github.com/lcompilers/lpython/issues/1996 for a general design. We'll refactor the above C into ASR->ASR passes, then it should work in C, LLVM and other backends backends automatically.

**Comment by certik** [comment]
@anutosh491 I think you just finished the first part of the project with #2094.

Now the next step is to figure out how to lift this symbolic support from the C backend into a new ASR->ASR pass that we need to write. That will consolidate all this symbolic support into just one file (the ASR pass) and it will make it work with any backend, including C and LLVM.

**Comment by certik** [comment]
The last comment was fixed in https://github.com/lcompilers/lpython/pull/2255. I think this issue is fixed.
