### ISSUE TITLE
Symbolic TODO

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2262]
* [x] basic_free_stack https://github.com/lcompilers/lpython/pull/2268
* [x] simplify the pass, currently it is about 2K lines, I think a lot of repetitions can be refactored. https://github.com/lcompilers/lpython/pull/2263
* [x] https://github.com/lcompilers/lpython/issues/1907
* [ ] examples don't work with `--fast`
