### ISSUE TITLE
Symbolics TODO

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2332]
* [ ] get the mrv() function finished that doesn't need the SubsSet (see my `gruntz2` branch)
* [ ] Implement missing ASR features (important: focus only on a clean ASR design, for now in the frontend support method calls, and maybe later we'll design a clean interface):
  * [ ] `e.has(x)`
  * [ ] `e.is_Mul`, `e.is_Add`, `e.is_Pow`
  * [ ] `isinstance(e, log)`, `isinstance(e, exp)`
  * [ ] `e.exp.args[0]`
  * [ ] `exponent = int(e.exp)`
  * [ ] Set of symbolic expressions (`{exp(x)}`)

**Comment by anutosh491** [comment]
Well if we plan on using `basic_get_args` for implemnting `e.exp` and `e.base` (instead of what I was trying to do in https://github.com/symengine/symengine/pull/1980), we would need a work around for the `CVecBasic` type just like we had one for the `basic` type.
If you remember, we introduced a workaround for declaring a basic variable as follows 
```
    _x: i64 = i64(0)
    x: CPtr = empty_c_void_p()
    p_c_pointer(pointer(_x, i64), x)
```

Now what `basic_get_args` does is, it takes in a pointer to `CVecBasic` and then it populates the value of `args` with the arguments.
```
//! Returns a CVecBasic of vec_basic given by get_args
CWRAPPER_OUTPUT_TYPE basic_get_args(const basic self, CVecBasic *args);
```
Hence we might need to think about a workaround for implementing `CVecBasic` in LPython.

**Comment by certik** [comment]
You can also write an auxiliary C function that does this, if it simplifies things.

**Comment by certik** [comment]
Regarding the `args`, let's first implement the following:
```
args: tuple[S] = (x**2).args
print(args[0], args[1])
```
Where we obtain the whole vector of arguments from SymEngine, and we convert it to a Python tuple. Then we just deal with a tuple. For that, we should first get tuples of type `S` working in LPython, that is, get this working first:
```
args: tuple[S] = (x, S(2))
print(args[0], args[1])
```
And then once that works, let's get `args: tuple[S] = (x**2).args` working. I think after that, the following will also automatically start working:
```
print((x**2).args[0], (x**2).args[1])
```

**Comment by certik** [comment]
I would add a new integration test `test_gruntz.py` and in there I would start implementing the `mrv` function, I would start small and then start adding things to it. Every time we discover something that does not work, I would isolate the bug, and add a dedicated separate test `test_symbolics_??.py` for it. That way every single new feature will be tested. And then in `test_gruntz.py` I would just keep improving the one `mrv` implementation.
