### ISSUE TITLE
LPython Tutorial checklist

### ISSUE THREAD

**Issue by Smit-create** [lcompilers/lpython#2432]
- [ ] Variables, Functions, loops
- [ ] Structs, enums, union
- [ ] List, dict, tuple, set
- [ ] arrays
- [ ] ccall, callable, lpython -- decorators
- [ ] generics
- [ ] symbolics
