### ISSUE TITLE
Class TODO list

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#2680]
* [ ] investigate how CPython declares member variables for classes
* [ ] use existing class support in ASR, hook it in AST->ASR, add tests
* [ ] identify what is missing (I think inheritance and some other things)
* [ ] implement those

**Comment by Thirumalai-Shaktivel** [comment]
Hey @tanay-man, you can start with a very simple code and try to compile that using LPython.
```py
class Test():
    i = 5

x = Test()
print(x.i)
```

```console
$ python test.py
5
```

This needs to statically typed to compile using LPython, So, we can do
```py
from lpython import i32

class Test():
    i: i32 = 5

x: Test = Test()
print(x.i)
```

```console
$ python test.py
5
```

Every LPython code must be compiled using CPython.
Now, you can use this code to start making the initial changes in LPython.
LPython throws the following error:
```console
$ lpython test.py 
semantic error: Only dataclass-decorated classes and Enum subclasses are supported.
  --> test.py:12:1 - 13:11
   |
12 |    class Test():
   |    ^^^^^^^^^^^^^...
...
   |
13 |     i: i32 = 5
   | ...^^^^^^^^^^^ 


Note: Please report unclear or confusing messages as bugs at
https://github.com/lcompilers/lpython/issues.
```

**Comment by tanay-man** [comment]
The above code is working. The `StructType` node of the ASR is used for the implementation of classes. According to the [documentation](https://docs.python.org/3/tutorial/classes.html), the members declared in the class body are static (common to all instances of the class) and those declared inside the constructor are specific to the instances (object members).
This is not true for the current implementation.

**Comment by Thirumalai-Shaktivel** [comment]
@tanay-man, now we have some initial implementation. You can start testing by adding some more tests, also port some tests from lfortran, like class_03, Inheritance, ...
