### ISSUE TITLE
Roadmap for the C backend user experience

### ISSUE THREAD

**Issue by certik** [lcompilers/lpython#545]
This issue is a roadmap for what we need to improve with regards to the C backend in LPython:

### High Priority

* [x] #544
* [x] Implement and test pointers (arguments)
* [x] Implement C structs (passing as arguments, etc.)
* [x] call other C functions that contain pointers, procedure calls, enums
* [x] C Structs interop: #606
* [x] Implement and test pointers (indexing): #546, #609

### Lower priority

* [ ] #541
* [ ] Implement procedure calls arguments
* [ ] Syntax+semantics of `p_c_pointer`: #592
* [x] Get all strings working, including the C interop: #671
* [ ] Pointer(x) does not update x: #670

**Comment by certik** [comment]
Smaller intermediate tasks:
* [ ] Sync ASR with LFortran
* [ ] Get the C backend compiling `test_c_interop_03`
* [ ] Get CPython running `test_c_interop_03`

**Comment by certik** [comment]
All the high priority features are implemented.

**Comment by certik** [comment]
Closing this in favor of #1575.
