### ISSUE TITLE
[Bug Tracking] LSP (VS Code)

### ISSUE THREAD

**Issue by ankitaS11** [lcompilers/lpython#763]
This issue will track bugs that are there in the current state of LSP in LPython:

* [ ] Document Symbol Lookup only works after saving the document. It should work without saving as well. (To reproduce: open VSCode, without saving the existing file, try pressing ctrl + shift + O - and document symbols don’t appear)
* [ ] Document Symbols get appended instead of being updated when the command is executed (ctrl + shift + O)

If anyone wants to work on these bugs, or contribute to the LSP, please reach out to me or @certik

**Comment by certik** [comment]
TODO:
* [ ] fix bugs (sometimes it doesn't seem to update / clean error messages when saved)
* [ ] the symbol table gets duplicated
* [ ] add tests (add a Python script that launches "lpython lsp ..." and sends JSON to it, and checks that a correct JSON gets returned)
* [ ] document in README how to test the LSP (how to compile the extension and test it out in Debug mode)
* [ ] polish the extension, move it under `lcompilers/lpython_vscode_extension` (or something like that), and publish on VSCode marketplace
